# In your static/admin/config.yml file

backend: 
    name: github
    repo: oNtAiR/attic

media_folder: static/assets
public_folder: assets

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "about"
        file: "content/home.md"
        fields:
          - {label: Intro title, name: title, widget: string}
          - {label: Intro text, name: intro, widget: text}
          - {label: Volunteer title, name: titlev, widget: string}
          - {label: Volunteer text, name: introv, widget: text}
          - {label: Donate title, name: titled, widget: string}
          - {label: Donate text, name: introd, widget: text}
          - {label: Hours title, name: titleh, widget: string}
          - {label: Hours text, name: introh, widget: text}
          - {label: Friends title, name: titlef, widget: string}
          - {label: Friends text, name: introf, widget: text}