# In your static/admin/config.yml file

backend: 
    name: github
    repo: oNtAiR/attic

media_folder: static/assets
public_folder: assets

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Home"
        name: "about"
        file: "content/home.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro text, name: intro, widget: text}
          